[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
# Main colors
primaryColor = "#ff8800"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1a1c23"
textColor = "#e2e8f0"

# Text elements
font = "sans serif"

# Interactive elements
base = "dark"

[global]
# Layout and spacing
layout = "wide"
disableWidgetStates = false
showSidebarNavigation = true

[deprecation]
showPyplotGlobalUse = false
